FROM debian:buster

RUN apt-get update
RUN apt-get install -y nginx openssl

EXPOSE 443
RUN mkdir /etc/nginx/ssl
RUN openssl req -newkey rsa:4096 -x509 -sha256 -days 365 -nodes \
       -out /etc/nginx/ssl/slord.crt \
       -keyout /etc/nginx/ssl/slord.key \
       -subj "/C=CA/ST=Quebec/L=Quebec/O=Les babouins en colere/CN=slord.42.fr"
COPY ./conf/default /etc/nginx/sites-enabled/default


CMD ["nginx", "-g", "daemon off;"]