version: '3'
services:
#   nginx:
#     container_name: nginx
#     build:
#       context: ./nginx
#     ports:
#       - "80:80"
#       - "443:443"
#     networks:
#       -inception



  # wordpress:
  #   container_name: wordpress
  #   build:
  #     context:
  #     ports:
  #     - "9000:9000"
 

  mariadb1:
    container_name: mariadb1
    build: 
      context: ./mariadb1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  
  