version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"


      
  wordpress:
    container_name: wordpress
    build:
      context: .
      ports:
      - "9000:9000"
 

  mariadb:
    container_name: mariadb
    build: 
      context: .
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  
  